github:
  api-base: https://api.github.com
  api-user: user_name
  api-key: the-api-key
  secret-token: my-token
scanoss:
  url: https://osskb.org
  token: my-scanoss-token
  comment_always: 1
  sbom_filename: SBOM.json
